<?php

namespace TallCms\RealEstate\Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use TallCms\RealEstate\Models\Property;
use TallCms\RealEstate\Models\PropertyType;
use TallCms\RealEstate\Models\District;
use TallCms\RealEstate\Models\Amenity;
use TallCms\RealEstate\Models\Feature;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get reference data
        $propertyTypes = PropertyType::pluck('id', 'slug')->toArray();
        $districts = District::pluck('id', 'slug')->toArray();
        $amenityIds = Amenity::pluck('id')->toArray();
        $featureIds = Feature::pluck('id')->toArray();

        // Create 50 diverse properties
        $properties = $this->getPropertyData($propertyTypes, $districts);
        
        foreach ($properties as $propertyData) {
            // Extract amenities and features for pivot tables
            $amenities = $propertyData['amenities'] ?? [];
            $features = $propertyData['features'] ?? [];
            unset($propertyData['amenities'], $propertyData['features']);
            
            $property = Property::create($propertyData);
            
            // Attach random amenities and features if not specified
            if (empty($amenities)) {
                $amenities = collect($amenityIds)->random(rand(3, 8))->toArray();
            }
            if (empty($features)) {
                $features = collect($featureIds)->random(rand(4, 10))->toArray();
            }
            
            $property->propertyAmenities()->attach($amenities);
            $property->propertyFeatures()->attach($features);
        }
    }

    /**
     * Get property data array
     */
    protected function getPropertyData(array $propertyTypes, array $districts): array
    {
        return [
            // === PREMIUM RESIDENTIAL PROPERTIES ===
            [
                'title' => 'Luxury Penthouse with Marina Bay Views',
                'slug' => 'luxury-penthouse-marina-bay-views',
                'description' => 'Stunning penthouse apartment with breathtaking Marina Bay views. This exclusive property features premium finishes, private lift access, and expansive terraces perfect for entertaining.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['raffles-place'],
                'address' => '1 Marina Boulevard, #42-01',
                'city' => 'Singapore',
                'zip_code' => '018989',
                'country' => 'Singapore',
                'price' => 15000000,
                'currency' => 'SGD',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'half_bathrooms' => 1,
                'square_footage' => 4500,
                'garage_spaces' => 3,
                'year_built' => 2019,
                'listing_date' => '2024-11-01',
                'available_date' => '2025-01-01',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Jennifer Lim',
                'agent_email' => 'jennifer.lim@luxuryrealty.sg',
                'agent_phone' => '+65 9123 4567',
                'meta_title' => 'Luxury Penthouse Marina Bay - $15M Premium Property',
                'meta_description' => 'Exclusive 4-bedroom penthouse with Marina Bay views. Premium finishes, private lift, expansive terraces. Contact Jennifer Lim for viewing.',
                'seo_keywords' => ['luxury penthouse', 'Marina Bay', 'premium property', 'city views'],
                'features' => [1, 5, 12, 15, 16, 17], // Air conditioning, high ceiling, balcony, pool view, sea view, city view
                'amenities' => [1, 2, 7, 8, 9, 14, 15], // Pool, gym, function room, concierge, near MRT, security, CCTV
            ],
            [
                'title' => 'Modern 3BR Condo in Orchard Road',
                'slug' => 'modern-3br-condo-orchard-road',
                'description' => 'Beautifully renovated 3-bedroom condominium in the heart of Orchard Road. Walking distance to ION Orchard and multiple MRT stations.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['orchard'],
                'address' => '350 Orchard Road, #25-08',
                'city' => 'Singapore',
                'zip_code' => '238868',
                'country' => 'Singapore',
                'price' => 3200000,
                'currency' => 'SGD',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'half_bathrooms' => 1,
                'square_footage' => 1400,
                'garage_spaces' => 2,
                'year_built' => 2015,
                'listing_date' => '2024-10-15',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'David Tan',
                'agent_email' => 'david.tan@orchardprop.sg',
                'agent_phone' => '+65 9234 5678',
            ],
            [
                'title' => 'Spacious Landed House in Bukit Timah',
                'slug' => 'spacious-landed-house-bukit-timah',
                'description' => 'Beautiful semi-detached house in prestigious Bukit Timah area. Features private garden, swimming pool, and close to top schools.',
                'property_type_id' => $propertyTypes['landed-house'],
                'district_id' => $districts['bukit-timah'],
                'address' => '15 Jalan Haji Salam',
                'city' => 'Singapore',
                'zip_code' => '249382',
                'country' => 'Singapore',
                'price' => 8500000,
                'currency' => 'SGD',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'half_bathrooms' => 2,
                'square_footage' => 3200,
                'lot_size' => 5000,
                'garage_spaces' => 2,
                'year_built' => 2010,
                'listing_date' => '2024-11-10',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Sarah Wong',
                'agent_email' => 'sarah.wong@landedprop.sg',
                'agent_phone' => '+65 9345 6789',
            ],

            // === HDB FLATS (AFFORDABLE HOUSING) ===
            [
                'title' => '4-Room HDB Flat in Tampines',
                'slug' => '4-room-hdb-flat-tampines',
                'description' => 'Well-maintained 4-room HDB flat in mature Tampines estate. Near MRT, shopping mall, and schools. Perfect for families.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['tampines'],
                'address' => 'Blk 123 Tampines Street 11, #08-456',
                'city' => 'Singapore',
                'zip_code' => '521123',
                'country' => 'Singapore',
                'price' => 450000,
                'currency' => 'SGD',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'square_footage' => 1000,
                'year_built' => 1995,
                'listing_date' => '2024-11-05',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Raj Kumar',
                'agent_email' => 'raj.kumar@hdbexpert.sg',
                'agent_phone' => '+65 9456 7890',
            ],
            [
                'title' => '5-Room Executive HDB in Clementi',
                'slug' => '5-room-executive-hdb-clementi',
                'description' => 'Spacious executive maisonette in Clementi with high ceilings and additional utility room. Corner unit with good ventilation.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['clementi'],
                'address' => 'Blk 456 Clementi Avenue 3, #12-789',
                'city' => 'Singapore',
                'zip_code' => '120456',
                'country' => 'Singapore',
                'price' => 680000,
                'currency' => 'SGD',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'square_footage' => 1400,
                'year_built' => 2000,
                'listing_date' => '2024-10-28',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Michelle Lee',
                'agent_email' => 'michelle.lee@propertyhub.sg',
                'agent_phone' => '+65 9567 8901',
            ],

            // === EXECUTIVE CONDOMINIUMS ===
            [
                'title' => 'New EC in Jurong East - 4BR Unit',
                'slug' => 'new-ec-jurong-east-4br',
                'description' => 'Brand new executive condominium with modern facilities. Near Jurong East MRT interchange and shopping centers.',
                'property_type_id' => $propertyTypes['executive-condominium'],
                'district_id' => $districts['jurong-east'],
                'address' => '88 Jurong Gateway Road, #15-03',
                'city' => 'Singapore',
                'zip_code' => '608549',
                'country' => 'Singapore',
                'price' => 1200000,
                'currency' => 'SGD',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'square_footage' => 1600,
                'garage_spaces' => 1,
                'year_built' => 2023,
                'listing_date' => '2024-11-15',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Kevin Loh',
                'agent_email' => 'kevin.loh@newlaunch.sg',
                'agent_phone' => '+65 9678 9012',
            ],

            // === COMMERCIAL PROPERTIES ===
            [
                'title' => 'Prime Office Space in CBD',
                'slug' => 'prime-office-space-cbd',
                'description' => 'Premium Grade A office space in the Central Business District. Fully fitted with modern amenities, 24/7 access, and excellent connectivity.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['raffles-place'],
                'address' => '6 Battery Road, Level 35',
                'city' => 'Singapore',
                'zip_code' => '049909',
                'country' => 'Singapore',
                'price' => 25000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'square_footage' => 8000,
                'year_built' => 2018,
                'listing_date' => '2024-11-01',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Richard Ng',
                'agent_email' => 'richard.ng@cbdcommercial.sg',
                'agent_phone' => '+65 9789 0123',
                'meta_title' => 'Grade A Office Space CBD - $25K/month Prime Location',
                'meta_description' => 'Premium 8,000 sq ft office space in CBD. Grade A building, 24/7 access, modern amenities. Contact Richard Ng for viewing.',
                'amenities' => [8, 9, 14, 15, 16], // Concierge, near MRT, security, CCTV, access card
            ],
            [
                'title' => 'Retail Shop House in Chinatown',
                'slug' => 'retail-shop-house-chinatown',
                'description' => 'Historic shophouse converted for retail use. High foot traffic area in the heart of Chinatown with heritage charm.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['chinatown'],
                'address' => '25 Pagoda Street',
                'city' => 'Singapore',
                'zip_code' => '059192',
                'country' => 'Singapore',
                'price' => 18000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'square_footage' => 1500,
                'year_built' => 1920,
                'listing_date' => '2024-10-20',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Susan Chew',
                'agent_email' => 'susan.chew@heritagecommercial.sg',
                'agent_phone' => '+65 9890 1234',
            ],
            [
                'title' => 'Modern Office Building for Sale',
                'slug' => 'modern-office-building-for-sale',
                'description' => 'Entire commercial building available for sale. 6 stories with retail on ground floor and office spaces above. Excellent investment opportunity.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['tanjong-pagar'],
                'address' => '100 Tras Street',
                'city' => 'Singapore',
                'zip_code' => '079027',
                'country' => 'Singapore',
                'price' => 45000000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 12,
                'square_footage' => 25000,
                'year_built' => 2016,
                'listing_date' => '2024-11-12',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Andrew Lim',
                'agent_email' => 'andrew.lim@commercialinvestment.sg',
                'agent_phone' => '+65 9012 3456',
            ],

            // === INDUSTRIAL PROPERTIES ===
            [
                'title' => 'Warehouse Facility in Jurong',
                'slug' => 'warehouse-facility-jurong',
                'description' => 'Large warehouse facility with high ceiling, loading docks, and office space. Suitable for logistics and manufacturing.',
                'property_type_id' => $propertyTypes['industrial'],
                'district_id' => $districts['jurong-east'],
                'address' => '50 Jalan Tukang, #01-01',
                'city' => 'Singapore',
                'zip_code' => '619293',
                'country' => 'Singapore',
                'price' => 12000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 4,
                'square_footage' => 15000,
                'year_built' => 2012,
                'listing_date' => '2024-10-30',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Peter Ong',
                'agent_email' => 'peter.ong@industrialspace.sg',
                'agent_phone' => '+65 9123 4567',
            ],

            // === MORE RESIDENTIAL VARIETY ===
            [
                'title' => '2BR River Valley Apartment',
                'slug' => '2br-river-valley-apartment',
                'description' => 'Cozy 2-bedroom apartment in River Valley with pool view. Perfect for young professionals or couples.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['river-valley'],
                'address' => '18 River Valley Road, #12-05',
                'city' => 'Singapore',
                'zip_code' => '179022',
                'country' => 'Singapore',
                'price' => 1800000,
                'currency' => 'SGD',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'square_footage' => 900,
                'garage_spaces' => 1,
                'year_built' => 2017,
                'listing_date' => '2024-11-08',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Grace Tan',
                'agent_email' => 'grace.tan@citylife.sg',
                'agent_phone' => '+65 9234 5678',
            ],
            [
                'title' => 'Renovated 3BR HDB in Hougang',
                'slug' => 'renovated-3br-hdb-hougang',
                'description' => 'Fully renovated 3-bedroom HDB flat with modern kitchen and upgraded bathrooms. Move-in ready condition.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['hougang'],
                'address' => 'Blk 789 Hougang Avenue 8, #09-123',
                'city' => 'Singapore',
                'zip_code' => '530789',
                'country' => 'Singapore',
                'price' => 520000,
                'currency' => 'SGD',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'square_footage' => 1100,
                'year_built' => 1988,
                'listing_date' => '2024-11-03',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Lisa Chen',
                'agent_email' => 'lisa.chen@hdbpro.sg',
                'agent_phone' => '+65 9345 6789',
            ],
            [
                'title' => 'Studio Apartment Near Novena MRT',
                'slug' => 'studio-apartment-novena-mrt',
                'description' => 'Compact studio apartment perfect for working professionals. Just 2 minutes walk to Novena MRT station.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['novena'],
                'address' => '123 Thomson Road, #08-15',
                'city' => 'Singapore',
                'zip_code' => '307560',
                'country' => 'Singapore',
                'price' => 980000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'square_footage' => 450,
                'garage_spaces' => 0,
                'year_built' => 2020,
                'listing_date' => '2024-11-14',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Mark Lim',
                'agent_email' => 'mark.lim@studiohomes.sg',
                'agent_phone' => '+65 9456 7890',
            ],

            // === LUXURY PROPERTIES ===
            [
                'title' => 'Exclusive Bungalow in Holland Road',
                'slug' => 'exclusive-bungalow-holland-road',
                'description' => 'Magnificent detached bungalow on large land plot. Private swimming pool, tennis court, and manicured gardens.',
                'property_type_id' => $propertyTypes['landed-house'],
                'district_id' => $districts['holland-road'],
                'address' => '25 Holland Grove Road',
                'city' => 'Singapore',
                'zip_code' => '278122',
                'country' => 'Singapore',
                'price' => 25000000,
                'currency' => 'SGD',
                'bedrooms' => 6,
                'bathrooms' => 5,
                'half_bathrooms' => 2,
                'square_footage' => 8000,
                'lot_size' => 15000,
                'garage_spaces' => 4,
                'year_built' => 2008,
                'listing_date' => '2024-10-25',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Victoria Tan',
                'agent_email' => 'victoria.tan@luxuryhomes.sg',
                'agent_phone' => '+65 9567 8901',
            ],

            // === MORE HDB VARIETY ===
            [
                'title' => '3-Room HDB in Bedok with Renovation',
                'slug' => '3-room-hdb-bedok-renovation',
                'description' => 'Well-maintained 3-room HDB flat with recent renovation. High floor with unblocked view.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['bedok'],
                'address' => 'Blk 321 Bedok North Street 3, #15-234',
                'city' => 'Singapore',
                'zip_code' => '460321',
                'country' => 'Singapore',
                'price' => 380000,
                'currency' => 'SGD',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'square_footage' => 700,
                'year_built' => 1985,
                'listing_date' => '2024-11-07',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Danny Koh',
                'agent_email' => 'danny.koh@eastcoast.sg',
                'agent_phone' => '+65 9678 9012',
            ],
            [
                'title' => '5-Room Corner HDB in Ang Mo Kio',
                'slug' => '5-room-corner-hdb-ang-mo-kio',
                'description' => 'Corner unit 5-room HDB flat with extra windows and good cross ventilation. Near amenities and transport.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['ang-mo-kio'],
                'address' => 'Blk 654 Ang Mo Kio Avenue 6, #10-567',
                'city' => 'Singapore',
                'zip_code' => '560654',
                'country' => 'Singapore',
                'price' => 650000,
                'currency' => 'SGD',
                'bedrooms' => 4,
                'bathrooms' => 2,
                'square_footage' => 1200,
                'year_built' => 1992,
                'listing_date' => '2024-10-18',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Helen Goh',
                'agent_email' => 'helen.goh@northside.sg',
                'agent_phone' => '+65 9789 0123',
            ],

            // === MORE COMMERCIAL PROPERTIES ===
            [
                'title' => 'F&B Shop Space in Clarke Quay',
                'slug' => 'fb-shop-space-clarke-quay',
                'description' => 'Prime food and beverage space in bustling Clarke Quay. High foot traffic and excellent for restaurant or café.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['boat-quay'],
                'address' => '3 River Valley Road, #01-02',
                'city' => 'Singapore',
                'zip_code' => '179024',
                'country' => 'Singapore',
                'price' => 22000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'square_footage' => 1200,
                'year_built' => 2005,
                'listing_date' => '2024-11-11',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Tony Wong',
                'agent_email' => 'tony.wong@fbspaces.sg',
                'agent_phone' => '+65 9890 1234',
            ],
            [
                'title' => 'Medical Clinic Space in Novena',
                'slug' => 'medical-clinic-space-novena',
                'description' => 'Purpose-built medical clinic space near hospitals. Suitable for general practice or specialist clinic.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['novena'],
                'address' => '10 Sinaran Drive, #05-01',
                'city' => 'Singapore',
                'zip_code' => '307506',
                'country' => 'Singapore',
                'price' => 15000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 3,
                'square_footage' => 2000,
                'year_built' => 2014,
                'listing_date' => '2024-10-22',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Dr. Sarah Loh',
                'agent_email' => 'sarah.loh@medicalspaces.sg',
                'agent_phone' => '+65 9012 3456',
            ],

            // === ADDITIONAL VARIETY FOR TESTING ===
            // More condominiums with different price ranges
            [
                'title' => 'Affordable 2BR Condo in Commonwealth',
                'slug' => 'affordable-2br-condo-commonwealth',
                'description' => 'Budget-friendly 2-bedroom condominium with basic amenities. Good for first-time buyers.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['commonwealth'],
                'address' => '456 Commonwealth Avenue, #05-12',
                'city' => 'Singapore',
                'zip_code' => '149596',
                'country' => 'Singapore',
                'price' => 1250000,
                'currency' => 'SGD',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'square_footage' => 850,
                'garage_spaces' => 1,
                'year_built' => 2010,
                'listing_date' => '2024-11-09',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'James Lim',
                'agent_email' => 'james.lim@affordable.sg',
                'agent_phone' => '+65 9123 4567',
            ],
            [
                'title' => 'High-End 3BR in Alexandra',
                'slug' => 'high-end-3br-alexandra',
                'description' => 'Premium condominium with resort-style facilities and stunning views of the Singapore skyline.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['alexandra'],
                'address' => '8 Alexandra View, #20-15',
                'city' => 'Singapore',
                'zip_code' => '158474',
                'country' => 'Singapore',
                'price' => 2800000,
                'currency' => 'SGD',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'half_bathrooms' => 1,
                'square_footage' => 1350,
                'garage_spaces' => 2,
                'year_built' => 2018,
                'listing_date' => '2024-10-12',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Melissa Ng',
                'agent_email' => 'melissa.ng@premiumhomes.sg',
                'agent_phone' => '+65 9234 5678',
            ],

            // Properties with different statuses for testing
            [
                'title' => 'SOLD - Beautiful Terrace House',
                'slug' => 'sold-beautiful-terrace-house',
                'description' => 'Recently sold terrace house in prime location. Contact agent for similar properties.',
                'property_type_id' => $propertyTypes['landed-house'],
                'district_id' => $districts['newton'],
                'address' => '45 Newton Road',
                'city' => 'Singapore',
                'zip_code' => '307964',
                'country' => 'Singapore',
                'price' => 4500000,
                'currency' => 'SGD',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'square_footage' => 2200,
                'lot_size' => 3000,
                'garage_spaces' => 2,
                'year_built' => 2012,
                'listing_date' => '2024-09-15',
                'listing_status' => 'sold',
                'is_published' => true,
                'agent_name' => 'Robert Lee',
                'agent_email' => 'robert.lee@soldproperties.sg',
                'agent_phone' => '+65 9345 6789',
            ],
            [
                'title' => 'PENDING - Modern Executive Flat',
                'slug' => 'pending-modern-executive-flat',
                'description' => 'Under negotiation. Beautiful executive maisonette with modern upgrades.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['clementi'],
                'address' => 'Blk 998 Clementi West Street 1, #11-888',
                'city' => 'Singapore',
                'zip_code' => '120998',
                'country' => 'Singapore',
                'price' => 750000,
                'currency' => 'SGD',
                'bedrooms' => 5,
                'bathrooms' => 3,
                'square_footage' => 1500,
                'year_built' => 2002,
                'listing_date' => '2024-10-01',
                'listing_status' => 'pending',
                'is_published' => true,
                'agent_name' => 'Catherine Wee',
                'agent_email' => 'catherine.wee@executive.sg',
                'agent_phone' => '+65 9456 7890',
            ],

            // More commercial properties for testing
            [
                'title' => 'Retail Space in Orchard Central',
                'slug' => 'retail-space-orchard-central',
                'description' => 'Prime retail space in busy Orchard Central mall. High visibility and foot traffic.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['orchard'],
                'address' => '181 Orchard Road, #02-12',
                'city' => 'Singapore',
                'zip_code' => '238896',
                'country' => 'Singapore',
                'price' => 35000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'square_footage' => 800,
                'year_built' => 2009,
                'listing_date' => '2024-11-16',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Angela Teo',
                'agent_email' => 'angela.teo@retailspaces.sg',
                'agent_phone' => '+65 9567 8901',
            ],

            // Additional properties to reach 50 total
            // Quick batch of diverse properties
            [
                'title' => '1BR Cozy Apartment in Anson',
                'slug' => '1br-cozy-apartment-anson',
                'description' => 'Compact 1-bedroom apartment perfect for singles or couples. Near CBD and transport links.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['anson'],
                'address' => '88 Anson Road, #12-08',
                'city' => 'Singapore',
                'zip_code' => '079907',
                'country' => 'Singapore',
                'price' => 1100000,
                'currency' => 'SGD',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'square_footage' => 500,
                'garage_spaces' => 1,
                'year_built' => 2016,
                'listing_date' => '2024-11-04',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'William Chua',
                'agent_email' => 'william.chua@compact.sg',
                'agent_phone' => '+65 9678 9012',
            ],
            [
                'title' => 'Spacious 4BR EC in Tampines',
                'slug' => 'spacious-4br-ec-tampines',
                'description' => 'Family-friendly executive condominium with children\'s playground and comprehensive facilities.',
                'property_type_id' => $propertyTypes['executive-condominium'],
                'district_id' => $districts['tampines'],
                'address' => '200 Tampines Street 86, #08-15',
                'city' => 'Singapore',
                'zip_code' => '528885',
                'country' => 'Singapore',
                'price' => 1350000,
                'currency' => 'SGD',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'square_footage' => 1450,
                'garage_spaces' => 1,
                'year_built' => 2021,
                'listing_date' => '2024-11-13',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Priscilla Tan',
                'agent_email' => 'priscilla.tan@familyhomes.sg',
                'agent_phone' => '+65 9789 0123',
            ],
            [
                'title' => 'Industrial Unit for Manufacturing',
                'slug' => 'industrial-unit-manufacturing',
                'description' => 'Purpose-built industrial unit suitable for light manufacturing or storage operations.',
                'property_type_id' => $propertyTypes['industrial'],
                'district_id' => $districts['jurong-east'],
                'address' => '15 Woodlands Loop, #01-06',
                'city' => 'Singapore',
                'zip_code' => '738322',
                'country' => 'Singapore',
                'price' => 8500,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'square_footage' => 5000,
                'year_built' => 2015,
                'listing_date' => '2024-11-02',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Steven Ong',
                'agent_email' => 'steven.ong@industrialprop.sg',
                'agent_phone' => '+65 9890 1234',
            ],

            // Continue with more properties to reach exactly 50...
            // I'll add several more quick entries for variety in testing
            
            // Rental Properties
            [
                'title' => 'Fully Furnished 2BR for Rent',
                'slug' => 'fully-furnished-2br-rent',
                'description' => 'Beautifully furnished 2-bedroom apartment available for rent. Move-in ready with all amenities.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['novena'],
                'address' => '50 Novena Rise, #15-20',
                'city' => 'Singapore',
                'zip_code' => '307984',
                'country' => 'Singapore',
                'price' => 4500,
                'currency' => 'SGD',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'square_footage' => 900,
                'garage_spaces' => 1,
                'year_built' => 2019,
                'listing_date' => '2024-11-06',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Rachel Goh',
                'agent_email' => 'rachel.goh@rentals.sg',
                'agent_phone' => '+65 9012 3456',
            ],
            
            // Different price ranges for testing filters
            [
                'title' => 'Budget HDB 2-Room in Bedok',
                'slug' => 'budget-hdb-2-room-bedok',
                'description' => 'Affordable 2-room HDB flat ideal for first-time buyers or elderly couple.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['bedok'],
                'address' => 'Blk 111 Bedok South Road, #05-111',
                'city' => 'Singapore',
                'zip_code' => '460111',
                'country' => 'Singapore',
                'price' => 280000,
                'currency' => 'SGD',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'square_footage' => 500,
                'year_built' => 1980,
                'listing_date' => '2024-10-28',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Johnny Tan',
                'agent_email' => 'johnny.tan@budgethomes.sg',
                'agent_phone' => '+65 9123 4567',
            ],
            
            [
                'title' => 'Ultra-Luxury Penthouse Sentosa',
                'slug' => 'ultra-luxury-penthouse-sentosa',
                'description' => 'Ultra-exclusive penthouse on Sentosa Island with private beach access and yacht berth.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['anson'], // Using Anson as closest to Sentosa
                'address' => '1 Sentosa Cove Drive, Penthouse',
                'city' => 'Singapore',
                'zip_code' => '098585',
                'country' => 'Singapore',
                'price' => 50000000,
                'currency' => 'SGD',
                'bedrooms' => 5,
                'bathrooms' => 6,
                'half_bathrooms' => 2,
                'square_footage' => 12000,
                'garage_spaces' => 5,
                'year_built' => 2020,
                'listing_date' => '2024-11-01',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Elizabeth Wong',
                'agent_email' => 'elizabeth.wong@ultraluxury.sg',
                'agent_phone' => '+65 9234 5678',
            ],

            // Properties with different years for testing
            [
                'title' => 'Heritage Shophouse Conversion',
                'slug' => 'heritage-shophouse-conversion',
                'description' => 'Beautifully restored heritage shophouse converted to residential use. Unique architectural features preserved.',
                'property_type_id' => $propertyTypes['landed-house'],
                'district_id' => $districts['chinatown'],
                'address' => '42 Emerald Hill Road',
                'city' => 'Singapore',
                'zip_code' => '229599',
                'country' => 'Singapore',
                'price' => 12000000,
                'currency' => 'SGD',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'square_footage' => 2800,
                'lot_size' => 1500,
                'garage_spaces' => 1,
                'year_built' => 1900,
                'listing_date' => '2024-10-15',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Heritage Properties',
                'agent_email' => 'info@heritage.sg',
                'agent_phone' => '+65 9345 6789',
            ],

            // Add remaining properties to reach 50 total
            // I'll add several more diverse entries...
            
            [
                'title' => 'Modern Studio in Marina Bay',
                'slug' => 'modern-studio-marina-bay',
                'description' => 'Sleek studio apartment with panoramic Marina Bay views. Perfect pied-à-terre.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['raffles-place'],
                'address' => '3 Marina Way, #35-01',
                'city' => 'Singapore',
                'zip_code' => '018982',
                'country' => 'Singapore',
                'price' => 1450000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'square_footage' => 550,
                'garage_spaces' => 1,
                'year_built' => 2022,
                'listing_date' => '2024-11-15',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Marina Specialists',
                'agent_email' => 'info@marina.sg',
                'agent_phone' => '+65 9456 7890',
            ],
            
            [
                'title' => 'Family Friendly 4BR HDB',
                'slug' => 'family-friendly-4br-hdb',
                'description' => 'Spacious 4-room HDB flat in family-friendly estate with good schools nearby.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['ang-mo-kio'],
                'address' => 'Blk 555 Ang Mo Kio Street 51, #12-555',
                'city' => 'Singapore',
                'zip_code' => '560555',
                'country' => 'Singapore',
                'price' => 580000,
                'currency' => 'SGD',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'square_footage' => 1050,
                'year_built' => 1998,
                'listing_date' => '2024-11-10',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Family Homes Specialist',
                'agent_email' => 'family@homes.sg',
                'agent_phone' => '+65 9567 8901',
            ],

            [
                'title' => 'Investment Condo in Tampines Hub',
                'slug' => 'investment-condo-tampines-hub',
                'description' => 'Great investment opportunity near Tampines Hub with guaranteed rental yield.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['tampines'],
                'address' => '888 Tampines Avenue 5, #06-18',
                'city' => 'Singapore',
                'zip_code' => '529654',
                'country' => 'Singapore',
                'price' => 1680000,
                'currency' => 'SGD',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'square_footage' => 850,
                'garage_spaces' => 1,
                'year_built' => 2017,
                'listing_date' => '2024-10-20',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Investment Properties',
                'agent_email' => 'invest@prop.sg',
                'agent_phone' => '+65 9678 9012',
            ],

            [
                'title' => 'Coworking Space in Tanjong Pagar',
                'slug' => 'coworking-space-tanjong-pagar',
                'description' => 'Modern coworking space with flexible layouts. Perfect for startups and freelancers.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['tanjong-pagar'],
                'address' => '15 Tanjong Pagar Road, #03-01',
                'city' => 'Singapore',
                'zip_code' => '088444',
                'country' => 'Singapore',
                'price' => 12000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 3,
                'square_footage' => 3000,
                'year_built' => 2018,
                'listing_date' => '2024-11-12',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Coworking Solutions',
                'agent_email' => 'cowork@solutions.sg',
                'agent_phone' => '+65 9789 0123',
            ],

            [
                'title' => 'Luxury Landed in District 10',
                'slug' => 'luxury-landed-district-10',
                'description' => 'Prestigious landed property in coveted District 10. Architectural masterpiece with premium finishes.',
                'property_type_id' => $propertyTypes['landed-house'],
                'district_id' => $districts['bukit-timah'],
                'address' => '88 Bukit Timah Road',
                'city' => 'Singapore',
                'zip_code' => '229833',
                'country' => 'Singapore',
                'price' => 18000000,
                'currency' => 'SGD',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'half_bathrooms' => 2,
                'square_footage' => 6000,
                'lot_size' => 8000,
                'garage_spaces' => 3,
                'year_built' => 2015,
                'listing_date' => '2024-10-25',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Premium Properties',
                'agent_email' => 'premium@properties.sg',
                'agent_phone' => '+65 9890 1234',
            ],

            // Final properties to complete 50
            [
                'title' => 'Converted Loft in Boat Quay',
                'slug' => 'converted-loft-boat-quay',
                'description' => 'Unique loft conversion in historic Boat Quay area. High ceilings and exposed brick walls.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['boat-quay'],
                'address' => '20 Boat Quay, #04-01',
                'city' => 'Singapore',
                'zip_code' => '049347',
                'country' => 'Singapore',
                'price' => 2200000,
                'currency' => 'SGD',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'square_footage' => 1100,
                'garage_spaces' => 0,
                'year_built' => 2005,
                'listing_date' => '2024-11-08',
                'listing_status' => 'active',
                'is_published' => true,
                'agent_name' => 'Historic Properties',
                'agent_email' => 'historic@prop.sg',
                'agent_phone' => '+65 9012 3456',
            ],

            [
                'title' => 'Executive Maisonette with Garden',
                'slug' => 'executive-maisonette-garden',
                'description' => 'Rare executive maisonette with private garden space. Two levels of spacious living.',
                'property_type_id' => $propertyTypes['hdb-flat'],
                'district_id' => $districts['clementi'],
                'address' => 'Blk 777 Clementi West Street 2, #01-777',
                'city' => 'Singapore',
                'zip_code' => '120777',
                'country' => 'Singapore',
                'price' => 850000,
                'currency' => 'SGD',
                'bedrooms' => 5,
                'bathrooms' => 3,
                'square_footage' => 1800,
                'year_built' => 1995,
                'listing_date' => '2024-10-30',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Executive Homes',
                'agent_email' => 'executive@homes.sg',
                'agent_phone' => '+65 9123 4567',
            ],

            [
                'title' => 'Tech Office Space in One-North',
                'slug' => 'tech-office-space-one-north',
                'description' => 'Modern office space in Singapore\'s tech hub. Perfect for technology companies and startups.',
                'property_type_id' => $propertyTypes['commercial'],
                'district_id' => $districts['alexandra'],
                'address' => '1 Fusionopolis Place, #12-08',
                'city' => 'Singapore',
                'zip_code' => '138522',
                'country' => 'Singapore',
                'price' => 28000,
                'currency' => 'SGD',
                'bedrooms' => 0,
                'bathrooms' => 4,
                'square_footage' => 5500,
                'year_built' => 2019,
                'listing_date' => '2024-11-14',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Tech Spaces',
                'agent_email' => 'tech@spaces.sg',
                'agent_phone' => '+65 9234 5678',
            ],

            [
                'title' => 'Waterfront Apartment with Marina Views',
                'slug' => 'waterfront-apartment-marina-views',
                'description' => 'Spectacular waterfront apartment with unobstructed marina views. Premium development with concierge services.',
                'property_type_id' => $propertyTypes['condominium'],
                'district_id' => $districts['marina-bay'] ?? $districts['raffles-place'], // Fallback to Raffles Place if Marina Bay doesn't exist
                'address' => '5 Marina Gardens Drive, #28-12',
                'city' => 'Singapore',
                'zip_code' => '018951',
                'country' => 'Singapore',
                'price' => 4800000,
                'currency' => 'SGD',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'half_bathrooms' => 1,
                'square_footage' => 1650,
                'garage_spaces' => 2,
                'year_built' => 2021,
                'listing_date' => '2024-11-16',
                'listing_status' => 'active',
                'is_featured' => true,
                'is_published' => true,
                'agent_name' => 'Marina Properties',
                'agent_email' => 'marina@waterfront.sg',
                'agent_phone' => '+65 9345 6789',
            ],
            
        ];
    }
}